# Generated by Django 6.0.5 on 2026-06-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warehouse_id",
                    models.IntegerField(
                        db_index=True, unique=True, verbose_name="ID склада"
                    ),
                ),
                (
                    "row_size",
                    models.FloatField(
                        default=3.0,
                        help_text="Расстояние между рядами стеллажей в метрах",
                        verbose_name="Размер ряда (м)",
                    ),
                ),
                (
                    "shelf_size",
                    models.FloatField(
                        default=0.8,
                        help_text="Глубина полки в метрах",
                        verbose_name="Размер полки (м)",
                    ),
                ),
                (
                    "cell_size",
                    models.FloatField(
                        default=1.2,
                        help_text="Высота ячейки в метрах",
                        verbose_name="Размер ячейки (м)",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Название склада",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Размер ячейки склада",
                "verbose_name_plural": "Размеры ячеек складов",
                "ordering": ["warehouse_id"],
            },
        ),
    ]
