# Generated by Django 6.0.6 on 2026-08-22 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forklift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('moving', 'Moving'), ('loading', 'Loading'), ('error', 'Error'), ('stopped', 'Stopped')], default='idle', max_length=20)),
                ('charge_level', models.FloatField(default=0)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('position_z', models.FloatField(default=0)),
                ('cell_x', models.IntegerField(default=0)),
                ('cell_y', models.IntegerField(default=1)),
                ('cell_z', models.IntegerField(default=0)),
                ('speed', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('origin_x', models.FloatField(default=0)),
                ('origin_y', models.FloatField(default=0)),
                ('origin_z', models.FloatField(default=0)),
                ('dest_x', models.FloatField()),
                ('dest_y', models.FloatField()),
                ('dest_z', models.FloatField()),
                ('dest_cell_x', models.IntegerField(default=1)),
                ('dest_cell_y', models.IntegerField(default=1)),
                ('dest_cell_z', models.IntegerField(default=1)),
                ('path_waypoints', models.JSONField(default=list)),
                ('frontend_advanced_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forklift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='forklift_dashboard_app.forklift')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
