# Generated by Django 6.0.6 on 2026-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift_dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dest_cell_x',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='dest_cell_y',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='dest_cell_z',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
