# Generated by Django 6.0.5 on 2026-06-15 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift_dashboard_app', '0002_task_dest_cell_x_task_dest_cell_y_task_dest_cell_z'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='forklift_id',
        ),
        migrations.AddField(
            model_name='forklift',
            name='charge_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='task',
            name='forklift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='forklift_dashboard_app.forklift'),
        ),
    ]
