# Generated by Django 6.0.5 on 2026-06-18 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forklift_dashboard_app", "0004_forklift_charge_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="dest_cell_x",
        ),
        migrations.RemoveField(
            model_name="task",
            name="dest_cell_y",
        ),
        migrations.RemoveField(
            model_name="task",
            name="dest_cell_z",
        ),
        migrations.RemoveField(
            model_name="task",
            name="forklift",
        ),
        migrations.AddField(
            model_name="task",
            name="forklift_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="forklift_dashboard_app.forklift",
            ),
        ),
    ]
