# Generated by Django 6.0.6 on 2026-07-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift_dashboard_app', '0005_task_path_waypoints_forklift_speed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='dest_cell_x',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='dest_cell_y',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='dest_cell_z',
            field=models.IntegerField(default=1),
        ),
    ]
