# Generated by Django 6.0.5 on 2026-06-26 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "forklift_dashboard_app",
            "0005_remove_task_dest_cell_x_remove_task_dest_cell_y_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="forklift_id",
        ),
        migrations.AddField(
            model_name="task",
            name="dest_cell_x",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="task",
            name="dest_cell_y",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="task",
            name="dest_cell_z",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="task",
            name="forklift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="forklift_dashboard_app.forklift",
            ),
        ),
    ]
