# Generated by Django 6.0.5 on 2026-07-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forklift_dashboard_app', '0006_alter_task_options_alter_task_dest_cell_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forklift',
            name='cell_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forklift',
            name='cell_y',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='forklift',
            name='cell_z',
            field=models.IntegerField(default=0),
        ),
    ]
